name = "DynamicDiscreteSamplers"
uuid = "02edb123-fbf3-4025-abe6-bed5b7376cdf"
authors = ["Lilith Orion Hafner <lilithhafner@gmail.com>, Adriano Meligrana <adrianomeligrana@proton.me> and contributors"]
version = "0.0.0"

[deps]
AliasTables = "66dad0bd-aa9a-41b7-9441-69ab47430ed8"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
AliasTables = "1"
MutableArithmetics = "1"
Random = "1.10.0"
julia = "1.10.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "HypothesisTests", "StableRNGs", "StatsBase", "StatsFuns", "Test"]
